/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "g.h"
#include "granular.h"
#include "khp.h"
#include "klp.h"

// Include compiled network files ------------------

#include "clone_networkdata.h"
#include "delay_networkdata.h"
#include "envin_networkdata.h"
#include "Filter.h"
#include "follower_networkdata.h"
#include "Gran.h"
#include "Granulator_networkdata.h"
#include "jdel.h"
#include "mod_networkdata.h"
#include "pitchshifter.h"
#include "postfollow_networkdata.h"
#include "Switch_networkdata.h"
#include "wdelaymod_networkdata.h"
#include "wdelay_networkdata.h"
#include "wdeleay2mod_networkdata.h"
#include "wdeleay2_networkdata.h"
#include "wdeleay3_networkdata.h"
#include "wdeleay_networkdata.h"
#include "WeirdDelay_networkdata.h"
#include "_4WaySwitch_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

